- name: Install and start MySQL on local machine
  hosts: localhost
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL dependencies
      apt:
        name:
          - mysql-server
          - python3-mysqldb

    - name: Start MySQL service
      service:
        name: mysql
        state: started
